version: "3.5"

services:
  web:
    build: .
    platform: linux/amd64
    tty: true
    container_name: notify
    restart: on-failure
    networks:
      - default
    command: bash -c "uvicorn main:app --reload --host 0.0.0 --port 8040"
    volumes:
      - .:/code
    ports:
      - "8040:8040"
    environment:
      TG_BOT_TOKEN: "test"
      TG_NOTIFY_CHANNEL: "test"
      DEBUG: "True"
      ORIGINS: "test"


volumes:
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
